import React,{useState} from 'react';
import {ChevronLeft,Bot,ArrowRight,Check,Sparkles,ArrowUpRight} from 'lucide-react';
import {TOPICS,LABELS,EXAMPLES,STAGES,go,Badge,Ring,ScoreBreakdown} from './ui';
export function NewTask({submit,busy}){
 const [title,setTitle]=useState(''),[raw,setRaw]=useState(''),[topic,setTopic]=useState(TOPICS[0]);
 return <div className="narrow"><button className="back" onClick={()=>go('catalog')}><ChevronLeft size={16}/>Каталог</button><div className="page-title"><div><div className="eyebrow">ШАГ 1 · СЫРАЯ ИДЕЯ</div><h1>У каждого квеста есть начало.</h1><p>Опишите потребность. Sana Bot поможет задать правильные вопросы.</p></div></div><form className="panel creation-form" onSubmit={e=>{e.preventDefault();submit({title,raw,topic});}}><div className="bot-heading"><span><Bot size={26}/></span><div><h3>Привет, я Sana!</h3><p>Расскажите, какую задачу вы хотите решить.</p></div></div><label>Название задачи<input required minLength={3} maxLength={120} placeholder="Например, AI-анализ отзывов клиентов" value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Направление<select value={topic} onChange={e=>setTopic(e.target.value)}>{TOPICS.map(t=><option key={t}>{t}</option>)}</select></label><label>Ваша идея<textarea required minLength={10} maxLength={5000} rows={5} placeholder="Хотим сделать AI для анализа отзывов клиентов…" value={raw} onChange={e=>setRaw(e.target.value)}/></label><div className="form-tip"><Sparkles size={16}/>Не нужно идеального ТЗ. Начните с нескольких предложений.</div><div className="form-actions"><button type="button" className="secondary" onClick={()=>{setTitle('AI-анализ отзывов клиентов');setRaw('Хотим сделать AI для анализа отзывов клиентов.');}}>Вставить демо-идею</button><button className="primary" disabled={busy}>Создать и уточнить <ArrowRight size={17}/></button></div></form></div>;
}
export function Editor({task,busy,save}){
 const [fields,setFields]=useState({...task.fields}),[title,setTitle]=useState(task.title),[topic,setTopic]=useState(task.topic),[confirmed,setConfirmed]=useState(false);
 const change=(k,v)=>{setFields(f=>({...f,[k]:v}));setConfirmed(false);};
 return <><button className="back" onClick={()=>go('task/'+task.id)}><ChevronLeft size={16}/>К задаче</button><div className="page-title"><div><div className="eyebrow">ШАГ 2 · УТОЧНИТЕ И ПОДТВЕРДИТЕ</div><h1>Прокачаем ваш challenge.</h1><p>Ответы сразу формируют карточку. Проверьте её перед подтверждением.</p></div><Badge task={task}/></div><form className="editor-grid" onSubmit={e=>{e.preventDefault();save({title,topic,fields,confirmed:true,version:task.version});}}><div className="panel editor-fields"><label>Название<input value={title} required minLength={3} maxLength={120} onChange={e=>{setTitle(e.target.value);setConfirmed(false);}}/></label><label>Направление<select value={topic} onChange={e=>{setTopic(e.target.value);setConfirmed(false);}}>{TOPICS.map(t=><option key={t}>{t}</option>)}</select></label><div className="bot-inline"><Bot size={25}/><div><b>Sana Bot · {task.ai_mode==='openai'?'OpenAI':'локальный режим'}</b><p>{task.questions.length} вопросов помогут собрать детали. Неизвестное можно оставить пустым.</p></div></div>{Object.entries(LABELS).map(([k,label])=><label key={k} id={'field-'+k}>{label}<span className="field-question">{task.questions.find(q=>q.field===k)?.question||'Проверьте и при необходимости дополните сведения.'}</span><textarea rows={k==='contact'?2:3} maxLength={3000} value={fields[k]} onChange={e=>change(k,e.target.value)} placeholder={EXAMPLES[k]}/></label>)}<label className="checkbox"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>Я проверил(а) карточку и подтверждаю достоверность заполненных полей.</span></label><button className="primary w-full" disabled={busy||!confirmed}><Check size={17}/>Подтвердить и пересчитать рейтинг</button></div><aside className="editor-side"><section className="panel"><div className="eyebrow">ПОДТВЕРЖДЁННЫЙ РЕЙТИНГ</div><Ring score={task.score} large/><p className="text-center muted">Изменится после вашего подтверждения.</p><ScoreBreakdown task={task}/></section><section className="demo-helper"><Sparkles size={20}/><h3>Пример для демонстрации</h3><p>Заполните карточку синтетическими ответами для сценария анализа отзывов. Проверьте их перед сохранением.</p><button type="button" className="secondary" onClick={()=>{setFields({...EXAMPLES});setConfirmed(false);}}>Вставить демо-ответы</button></section></aside></form></>;
}
export function ProposalForm({task,team,busy,error,submit}){
 const [idea,setIdea]=useState(''),[plan,setPlan]=useState(''),[duration,setDuration]=useState(''),[prototype,setPrototype]=useState('');
 return <form onSubmit={e=>{e.preventDefault();submit({idea,plan,duration,prototype:prototype.trim()||null});}}><div className="eyebrow">STUDENT PROPOSAL</div><h2 className="mt-2">Предложите своё решение</h2><p className="muted mb-5">{team?.name} → {task.title}</p>{error&&<p className="form-error" role="alert">{error}</p>}<label>Идея решения<textarea required minLength={15} maxLength={3000} rows={3} value={idea} onChange={e=>setIdea(e.target.value)}/></label><label>План работы<textarea required minLength={15} maxLength={3000} rows={3} value={plan} onChange={e=>setPlan(e.target.value)}/></label><label>Срок<input required minLength={3} maxLength={100} placeholder="Например, 3 недели" value={duration} onChange={e=>setDuration(e.target.value)}/></label><label>Ссылка на прототип · необязательно<input type="url" maxLength={2000} placeholder="https://…" value={prototype} onChange={e=>setPrototype(e.target.value)}/></label><button className="primary w-full" disabled={busy}>Отправить отклик <ArrowUpRight size={17}/></button></form>;
}
export function ProgressForm({app,busy,error,submit}){
 const choices=Object.keys(STAGES).filter(s=>!app.milestones.some(m=>m.stage===s));
 const [stage,setStage]=useState(choices[0]),[evidence,setEvidence]=useState(''),[confirmed,setConfirmed]=useState(false);
 return <form onSubmit={e=>{e.preventDefault();submit({stage,evidence,confirmed:true});}}><div className="eyebrow">ПОДТВЕРЖДЕНИЕ БИЗНЕСОМ</div><h2 className="mt-2 mb-4">Реальный прогресс → XP</h2>{error&&<p className="form-error" role="alert">{error}</p>}<label>Завершённый этап<select value={stage} onChange={e=>setStage(e.target.value)}>{choices.map(s=><option key={s} value={s}>{STAGES[s]} · +{s==='discovery'?50:s==='prototype'?100:150} XP</option>)}</select></label><label>Что проверено и принято<textarea required minLength={15} maxLength={2000} rows={4} value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="Опишите проверенный результат. Можно добавить ссылку на артефакт."/></label><label className="checkbox"><input required type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>Я проверил(а) результат и подтверждаю выполнение этапа.</span></label><button className="primary w-full" disabled={busy||!confirmed}>Подтвердить и начислить XP</button></form>;
}
