import React,{useEffect,useRef} from 'react';
import {Sprout,Hammer,Rocket,Gem,Coins,Check,Target,Trophy,Layers,X,ArrowUpRight,Users} from 'lucide-react';
export const TOPICS=['AI / NLP','Data Science','Web','Education','Sustainability'];
export const LEVELS=['Idea','Builder','Launch Ready','Gold Challenge'];
export const LABELS={context:'Контекст',need:'Потребность',data:'Данные и материалы',result:'Ожидаемый результат',success:'Критерии успеха',constraints:'Ограничения',users:'Пользователи',contact:'Контакт',interaction:'Формат консультаций',feedback:'Порядок обратной связи'};
export const EXAMPLES={context:'Менеджеры вручную читают 5000 отзывов клиентов каждый месяц.',need:'Сократить время разбора отзывов и быстрее находить причины жалоб.',data:'CSV с 5000 обезличенными отзывами; 300 размеченных примеров для проверки.',result:'Веб-панель с темами, тональностью отзывов и экспортом отчёта в CSV.',success:'F1 не ниже 0.85 на 300 отложенных размеченных отзывах.',constraints:'4 недели, Python и React. Только обезличенные данные, без внешнего хранения.',users:'Менеджеры клиентской поддержки и руководитель отдела качества.',contact:'mentor@example.com',interaction:'Видеовстреча с наставником каждую среду на 30 минут.',feedback:'Руководитель поддержки проверяет каждый этап за 2 рабочих дня.'};
export const PRIZES={highlight:'Неоновая рамка',aurora:'Aurora Skin',pixel:'Pixel Badge',spotlight:'Spotlight на 24 часа'};
export const STAGES={discovery:'Исследование',prototype:'Прототип',delivery:'Передача результата'};
export const go=p=>{location.hash=p;};
export const date=s=>new Date(s).toLocaleDateString('ru-RU',{day:'numeric',month:'short'});
export const spotlight=t=>t.spotlight_until&&new Date(t.spotlight_until)>new Date();
export function LevelIcon({index,...props}){const C=[Sprout,Hammer,Rocket,Gem][index]||Sprout;return <C {...props}/>;}
export function Badge({task}){return <span className={'badge level-'+task.level_index}><LevelIcon index={task.level_index} size={13}/>{task.level}</span>;}
export function Ring({score,large=false}){return <div className={'ring '+(large?'large':'')} style={{'--score':score+'%'}}><div><strong>{score}</strong><small>/ 100</small></div></div>;}
export function Modal({children,close}){const ref=useRef();useEffect(()=>{ref.current.showModal();},[]);return <dialog ref={ref} onCancel={close} onClick={e=>{if(e.target===ref.current)close();}}><button aria-label="Закрыть" className="icon-btn modal-close" onClick={close}><X size={20}/></button>{children}</dialog>;}
export function Empty({text,action,actionText}){return <div className="empty"><Layers size={28}/><p>{text}</p>{action&&<button className="secondary" onClick={action}>{actionText}</button>}</div>;}
export function Status({status}){return <span className={'status '+status}>{status==='selected'?'Выбрана':status==='rejected'?'Отклонён':'На рассмотрении'}</span>;}
export function ScoreBreakdown({task}){return <div className="score-breakdown">{task.breakdown.map(r=><div key={r.key}><div><span>{r.label}</span><b>{r.points}<small>/{r.weight}</small></b></div><div className="progress-track"><span style={{width:r.points/r.weight*100+'%'}}/></div>{r.missing.length>0&&<small className="missing">Уточнить: {r.missing.map(k=>LABELS[k].toLowerCase()).join(', ')}</small>}</div>)}<details className="rubric"><summary>Как считаются баллы?</summary><p>Контекст и потребность: по 10. Данные: 20. Результат: 15. Критерии: 15. Ограничения: 10. Пользователи: 10. Связь: контакт 4 + консультации 3 + обратная связь 3.</p><p>Минимум 12 символов в основных полях; 5 — пользователи, 3 — контакт, 8 — формат и обратная связь. Критерий успеха содержит число. Пустые поля, «не знаю», «уточним позже», «нет информации», «не определено» дают 0.</p><p>Проверка полноты MVP, а не экспертная оценка смысла. Баллы начисляются после подтверждения человеком.</p></details></div>;}
export function QuestList({task}){return <div className="quest-grid">{task.quests.map(q=><div className={'quest '+(q.done?'done':'')} key={q.key}><span className="quest-check">{q.done?<Check size={15}/>:<Target size={15}/>}</span><div><strong>{q.title}</strong><small>{q.done?'Награда получена':'Подтвердите раздел полностью'}</small></div><span className="quest-value">+{q.coins}<Coins size={13}/><small>+{q.xp} XP</small></span></div>)}</div>;}
export function TaskCard({task:t,count}){return <article className={'task-card evolution-'+t.level_index+' '+t.cosmetics.join(' ')}><div className="card-top"><span className={'company-icon topic-'+TOPICS.indexOf(t.topic)}>{t.company.split(' ').map(s=>s[0]).join('').slice(0,2)}</span><div><strong>{t.company}</strong><small>{t.topic}</small></div><button className="icon-btn card-arrow" aria-label={'Открыть '+t.title} onClick={()=>go('task/'+t.id)}><ArrowUpRight size={20}/></button></div><a className="card-title" href={'#task/'+t.id}>{t.title}</a><p className="card-description">{t.fields.need||t.fields.context||t.raw}</p><div className="tags"><span>{t.topic}</span>{t.level_index===3&&<span className="gold-tag"><Gem size={12}/>Priority</span>}{spotlight(t)&&<span>Spotlight</span>}{t.cosmetics.includes('pixel')&&<span>✦ Pixel</span>}</div><div className="readiness"><div><span>Task Readiness</span><b>{t.score}<small>/100</small></b></div><div className="progress-track"><span style={{width:t.score+'%'}}/></div></div><div className="card-bottom"><Badge task={t}/><span><Users size={14}/>{count} откликов</span></div></article>;}
