import React from 'react';
import {Plus,ArrowUpRight,Trophy,Coins,Zap} from 'lucide-react';
import {go,date,Badge,LevelIcon,QuestList,Empty} from './ui';
import {Application} from './Detail';
export function Dashboard({tasks,apps,teams,role,team,busy,decide,progress}){
 const shown=apps.filter(a=>role==='Business'||a.team_id===team);
 return <><div className="page-title"><div><div className="eyebrow">{role==='Business'?'BUSINESS WORKSPACE':'STUDENT WORKSPACE'}</div><h1>{role==='Business'?'Ваши идеи. Ваши команды.':'От идеи — к первому прототипу.'}</h1><p>{role==='Business'?'Улучшайте задачи, сравнивайте отклики и выбирайте партнёров.':'XP начисляется за этапы, подтверждённые бизнесом.'}</p></div>{role==='Business'&&<button className="primary" onClick={()=>go('new')}><Plus size={17}/>Новая задача</button>}</div>
 {role==='Business'&&<><div className="section-heading"><h2>Мои задачи</h2><span className="muted">Демо: единый кабинет бизнеса</span></div><div className="task-table">{tasks.map(t=><div key={t.id}><div className="table-title"><span className={'tiny-icon level-'+t.level_index}><LevelIcon index={t.level_index} size={20}/></span><div><button className="text-button" onClick={()=>go('task/'+t.id)}>{t.title}</button><small>{t.company} · {t.published?'Опубликована':'Черновик'}</small></div></div><Badge task={t}/><strong>{t.score}/100</strong><button className="secondary" onClick={()=>go('edit/'+t.id)}>Улучшить <ArrowUpRight size={14}/></button></div>)}</div></>}
 <div className="section-heading mt-8"><h2>{role==='Business'?'Отклики команд':'Мои отклики'} <span>{shown.length}</span></h2>{role==='Business'&&<span className="muted">Выберите одну, несколько или ни одной команды</span>}</div>
 <div className="applications">{shown.map(a=><Application key={a.id} app={a} task={tasks.find(t=>t.id===a.challenge_id)} team={teams.find(t=>t.id===a.team_id)} role={role} busy={busy} decide={status=>decide(a.id,status)} progress={()=>progress(a)}/>)}</div>
 {!shown.length&&<Empty text="Пока нет откликов. Найдите интересный challenge в каталоге." action={()=>go('catalog')} actionText="Открыть каталог"/>}</>;
}
export function Quests({tasks,wallet,role,selectedTeam}){
 return <><div className="page-title"><div><div className="eyebrow">В КАЖДОЙ ДЕТАЛИ — ПРОГРЕСС</div><h1>Маленькие квесты. <span>Большой результат.</span></h1><p>{role==='Business'?'Coins открывают оформление. Readiness растёт от полноты карточки.':'Исследование +50 XP · Прототип +100 XP · Передача результата +150 XP'}</p></div><div className="quest-total"><Coins/> {wallet.coins}<small>Sana Coins</small></div></div>
 {role==='Business'?<><div className="quest-task-list">{tasks.map(t=><section className="panel" key={t.id}><div className="section-heading"><div><Badge task={t}/><h3 className="mt-3">{t.title}</h3></div><button className="secondary" onClick={()=>go('task/'+t.id)}>Открыть <ArrowUpRight size={16}/></button></div><QuestList task={t}/><div className="achievement-row">{t.achievements.map(a=><span key={a}><Trophy size={14}/>{a}</span>)}</div></section>)}</div><h2 className="mt-8 mb-4">История Coins и XP</h2><div className="panel history-ledger">{[...wallet.history].reverse().slice(0,30).map((e,i)=><div key={i}><span>{e.title}<small>{date(e.at)}</small></span><b className={e.coins>=0?'green-text':''}>{e.coins>0?'+':''}{e.coins} Coins · +{e.xp} XP</b></div>)}</div></>:<section className="panel"><h2>{selectedTeam?.name} · {selectedTeam?.xp||0} XP</h2><p className="my-4">Предоставьте бизнесу результат этапа. Представитель бизнеса проверит его и вручную подтвердит прогресс выбранного отклика.</p><button className="primary" onClick={()=>go('dashboard')}>Мои отклики <ArrowUpRight size={16}/></button></section>}</>;
}
export function Teams({teams,role,team,choose}){
 return <><div className="page-title"><div><div className="eyebrow">BUILD TOGETHER</div><h1>Команды, которые создают.</h1><p>Навыки помогают найти общий язык. Решение о сотрудничестве принимает бизнес.</p></div></div><div className="cards">{teams.map((t,i)=><section className="panel team-card" key={t.id}><span className={'team-avatar tone-'+i}>{t.name.split(' ').map(s=>s[0]).join('').slice(0,2)}</span><h2>{t.name}</h2><p>{t.interests.join(' · ')}</p><div className="tags">{t.skills.map(s=><span key={s}>{s}</span>)}</div><div className="team-footer"><span><Zap size={16}/>{t.xp} XP</span><b>Level {1+Math.floor(t.xp/200)}</b></div>{role==='Student'&&<button className={team===t.id?'secondary':'primary'} disabled={team===t.id} onClick={()=>choose(t.id)}>{team===t.id?'Ваша демо-команда':'Выбрать демо-команду'}</button>}</section>)}</div></>;
}
